### ISSUE TITLE
How to get the weights of signatures contributing to each tumor sample

### ISSUE THREAD

**Issue by JiaweiDai-create** [broadinstitute/getzlab-SignatureAnalyzer#23]
Hi,
    I want to get the weights of signatures contributing to each tumor sample. And I found that the output 
 of **_pd.read_hdf('nmf_output.h5', 'H')_** or **_pd.read_hdf('nmf_output.h5', 'Hraw')_** maight be the weights. But I am not much sure about that.
    If it's correct, which one is the final weight matix? Thank you!

**Comment by shankara-a** [comment]
Apologies for the late reply - `pd.read_hdf('nmf_output.h5', 'H')` will give you the final weights after these have been normalized wrt. the W Matrix.

Specific details and code with comments for the function that does this transferring of weights may be found [here](https://github.com/broadinstitute/getzlab-SignatureAnalyzer/blob/0253dec91206bd496921a6635faf3e26d17bda00/signatureanalyzer/utils.py#L91).
